### ISSUE TITLE
9주차 중간 보고서 작성

### ISSUE THREAD

**Issue by guswhdleee** [shin6949/capstone2#2]
### 9주차 팀 수행 일지 
9주차 팀 수행 일지 작성한 파일 공유합니다. 수정 사항 말씀 부탁합니다. 

---
**9주차 팀 수행 일지**
HWP: https://shorturl.at/diBPX
PDF: https://shorturl.at/dDUV3

**Comment by shin6949** [comment]
@guswhdleee 
* 2번 '데이터 테이블 구조 변경'을 'DB 테이블 구조 변경'으로 제목을 변경  
* 2번의 내용을 "게시글에 첨부한~~"에서 "게시글에 올릴 수 있는 사진의 갯수를 확대하고, 사진 별로 위치를 기재하기 위해서 DB의 구조 변경이 불가피하여, 아래와 같이 변경을 결정하였음."으로 변경
* 이전에 공유한 필기한 그림 첨부 부탁. 파일이 필요하면 [여기](shorturl.at/bgvT9) 참고

**Comment by guswhdleee** [comment]
@shin6949 
변경하여 다시 전달하겠음
hwp : https://shorturl.at/tyzNW
pdf : https://shorturl.at/ilrzQ

**Comment by shin6949** [comment]
수정 확인하였고 추가 개선 사항 없으니 제출하겠음.

**Comment by shin6949** [comment]
중간 보고서를 요구하였기 때문에 중간 보고서를 제출함.

---
### 중간 보고서 파일
HWP: https://shorturl.at/qAK49
PDF: https://shorturl.at/jrFZ5
