### ISSUE TITLE
회원가입 화면에서 사진이 안나오는 현상

### ISSUE THREAD

**Issue by guswhdleee** [shin6949/capstone2#29]
회원가입 화면에서 메인화면에 나타나던 사진이 사라지는 현상이 있습니다.

**Comment by guswhdleee** [comment]
![KakaoTalk_20211028_210825051](https://user-images.githubusercontent.com/51352707/139253298-91cb63c6-a9d3-49bd-af37-52c8efed8f32.png)

**Comment by shin6949** [comment]
이 문제는 지속적으로 문제가 됐던 것인데, Cloud의 Blob Storage로 Image의 위치를 변경하여 해결해보겠습니다.

**Comment by shin6949** [comment]
36c8834 Commit을 통해 해결되었습니다. static image를 Cloud로 이주 조치하여, 간혹 생겼던 참조 에러를 해결하였습니다.
