### ISSUE TITLE
댓글 작성 시도시 새로 고침 발생

### ISSUE THREAD

**Issue by guswhdleee** [shin6949/capstone2#30]
게시글에 댓글작성을 시도 할 시, 새로고침 되는 현상이 있습니다.

https://user-images.githubusercontent.com/51352707/139254277-4f977b6b-98e9-4091-bae6-fd41de474329.mp4

**Comment by shin6949** [comment]
319f6f7 Commit으로 해결완료 되었습니다. Frontend 단에서 a 태그의 끝을 명시하였습니다.
