### ISSUE TITLE
회원정보 수정 시 반영이 안되는 현상

### ISSUE THREAD

**Issue by guswhdleee** [shin6949/capstone2#32]
회원 정보 수정 후, 다시 회원 정보 수정란에 들어가 보면 전에 수정했던 정보가 반영이 되지 않는 현상이 있습니다.

**Comment by shin6949** [comment]
이슈를 해결할려고 했으나 mustache 관련해서 에러가 지속적으로 발생하여 회원 정보 수정 기능을 간소화 할 필요가 있을 것으로 보임.

**Comment by shin6949** [comment]
6d7187f Commit으로 해결되었습니다. User의 정보를 넣을 수 있는 공간을 줄이고, mustache의 Error를 우회하여 재작성하였습니다.
