### ISSUE TITLE
10주차 팀 수행일지 작성

### ISSUE THREAD

**Issue by guswhdleee** [shin6949/capstone2#42]
Close된 이슈들을 참고하여 10주차 팀 수행일지 작성

**Comment by guswhdleee** [comment]
10주차 팀 수행일지 작성했습니다. 피드백 받습니다.

hwp : https://shorturl.at/lzHLW
pdf : https://shorturl.at/bkJLP

**Comment by shin6949** [comment]
1번 내용에 Git Issues에서 Tag를 Bug으로 한정 시키고, 해결한 리스트라고 해서 보여주면 될 것 같습니다.

**Comment by guswhdleee** [comment]
수정하여 다시 올려드립니다. 피드백 환영
hwp : https://shorturl.at/gkyEX
pdf : https://shorturl.at/dgwFN
