### ISSUE TITLE
위치선택 부분 엔터오류

### ISSUE THREAD

**Issue by hue412** [shin6949/capstone2#45]
location/find 부분에서 위치 입력하고 엔터치면 다시 목포 시청뜨는 현상발생

**Comment by shin6949** [comment]
Frontend Error로 Upload 프로세스를 개선할 예정이기 때문에 이 부분을 당장 수정하기 보다는 개선 후, 재발하는지 확인이 필요합니다.

**Comment by shin6949** [comment]
d9af31a Commit으로 해결되었습니다.
