### ISSUE TITLE
탐색 페이지 내의 공란

### ISSUE THREAD

**Issue by guswhdleee** [shin6949/capstone2#48]
탐색 페이지 내에서 사진 위치에 빈 공간이 발생하는 현상이 있습니다.
![image](https://user-images.githubusercontent.com/51352707/140615523-6228dbab-66dd-4f90-8a57-bc077a83d572.png)

**Comment by shin6949** [comment]
이 부분도 재현되지 않습니다. 공란과 연결되는 URL을 올려주시면 확인이 편할 것 같습니다.

**Comment by guswhdleee** [comment]
https://user-images.githubusercontent.com/51352707/140831312-e7ff07ee-cc33-4c3d-b7bb-fd80074b8819.mp4

문제가 발생하는 동영상입니다.
테스트를 진행했던 계정은
id : asdf6
pw : asdf6
입니다.

**Comment by shin6949** [comment]
DB의 Post와 Image가 연결되지 않아 생기는 현상으로 추측하였으나 확인해보니 게시글에 Image가 2개 이상인 경우 이를 세로로 표출하면서 생기는 문제로 보입니다.

**Comment by shin6949** [comment]
7fc4eb Commit으로 해결되었습니다.
위 코멘트와 같이 Image가 Null 상태라서 생긴 문제로 추측하였지만, 실제로는 Image가 2개 이상인 글을 불러왔을 때, 첫번째 사진만 보여져야하지만, 모든 사진이 보여지면서 생겼던 문제로, 첫번째 사진만 표출되도록 설정하여 해결하였음.
