### ISSUE TITLE
타 사용자가 프로필 사진을 변경 할 수 있는 현상

### ISSUE THREAD

**Issue by guswhdleee** [shin6949/capstone2#49]
실제로 반영까지 되지는 않지만, 타 사용자가 다른 사용자의 프로필 사진에 접근이 가능한 현상이 있습니다.

**Comment by shin6949** [comment]
제 환경에서는 확인되지 않습니다. 재현 과정을 상세히 설명하시기 바랍니다.

**Comment by guswhdleee** [comment]
https://user-images.githubusercontent.com/51352707/140832820-5ab872c4-f073-45bd-8229-3da39a685655.mp4



영상 첨부하도록 하겠습니다.

**Comment by shin6949** [comment]
77fc4eb Commit으로 해결되었습니다.
profile에서 본인의 프로필을 보는 것이 아닌 상태임에도 프로필 사진을 변경할 수 있는 form이 보이고 있기 때문에 생기는 문제로, 유효하지 않는 경우 form 데이터가 보이지 않도록 조치하여 해결하였습니다.
