### ISSUE TITLE
11주차 팀수행일지

### ISSUE THREAD

**Issue by guswhdleee** [shin6949/capstone2#51]
11주차 팀수행일지를 작성합니다.

**Comment by guswhdleee** [comment]
작성완료했습니다. 각종 피드백 환영 합니다
hwp : https://shorturl.at/fjuET
pdf : https://shorturl.at/yBCU4

**Comment by shin6949** [comment]
저는 이대로 제출해도 될 것 같습니다.
@hue412 님의 의견을 기다립니다.

**Comment by guswhdleee** [comment]
23시에 제출하고, 이슈 닫도록 하겠습니다.

**Comment by guswhdleee** [comment]
제출 완료.
