### ISSUE TITLE
프로필 사진 무한 로딩

### ISSUE THREAD

**Issue by guswhdleee** [shin6949/capstone2#64]
프로필 사진이 있을 경우에는 상관이 없지만, 프로필 사진이 기본 이미지인 상태에서 회원 정보 수정을 시도 할 경우, 기본 이미지를 불러오지 못하는 오류가 있습니다.
![image](https://user-images.githubusercontent.com/51352707/142978373-023b3c11-5f5d-4408-81de-bc8ced509395.png)
이미지가 미리 설정된 경우에는 오류가 나타나지 않습니다.
![image](https://user-images.githubusercontent.com/51352707/142978450-9b83874d-806f-4e5e-ba7d-765c02c7ae8a.png)
하지만 기본 이미지일 경우 무한 로딩이 발생합니다.

**Comment by shin6949** [comment]
profile-edit에서 프로필 사진을 표시할 때 사용하는 링크에 공백이 삽입되어 생긴 문제로 곧 해결할 예정입니다.

**Comment by shin6949** [comment]
acbe674 Commit으로 해결되었습니다.
